SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Schema
DROP SCHEMA IF EXISTS `oasis`;
CREATE SCHEMA IF NOT EXISTS `oasis` DEFAULT CHARACTER SET utf8;
USE `oasis`;

-- Table user
CREATE TABLE IF NOT EXISTS `oasis`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `age` INT NOT NULL,
  `weight` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `belt` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`)
)ENGINE = InnoDB;

-- Table championship
CREATE TABLE IF NOT EXISTS `oasis`.`championship` (
  `idchampionship` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `date` DATE NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idchampionship`)
)ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;